#!/bin/bash

rm -r docs/source
rm -r docs/_*
rm docs/*.html
rm docs/objects.inv
rm docs/searchindex.js
rm docs/.nojekyll

cp -r website_source/source docs/.
mv docs html
cd html
make html
touch .nojekyll
cd ..
mv html docs
