#!/bin/bash
cd ..

rm -r docs/source
rm -r docs/_*
rm docs/*.html
rm docs/objects.inv
rm docs/searchindex.js
rm docs/.nojekyll

mkdir docs
cp -r website_source/source docs/.
cd docs
sphinx-build -b html source .
touch .nojekyll
cd ..
